#!/usr/bin/env bash
# Refresh the committed weirdgloop data snapshot from the dev submodule.
# Usage: tools/update-data.sh [<weirdgloop-commit>]
# With an argument, checks the submodule out at that commit first.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SUB="$REPO_ROOT/tools/upstream"
DEST="$REPO_ROOT/src/main/resources/org/bossbis/data"

if [ "${1:-}" != "" ]; then
	git -C "$SUB" fetch origin "$1"
	git -C "$SUB" checkout "$1"
fi

mkdir -p "$DEST"
for f in equipment.json monsters.json equipment_aliases.json spells.json; do
	cp "$SUB/cdn/json/$f" "$DEST/$f"
done

COMMIT="$(git -C "$SUB" rev-parse HEAD)"
DATE="$(git -C "$SUB" show -s --format=%cs HEAD)"
cat > "$DEST/data-version.properties" <<EOF
# Generated by tools/update-data.sh — do not edit by hand.
weirdgloop.commit=$COMMIT
weirdgloop.snapshotDate=$DATE
EOF

echo "Copied 4 JSON files + data-version.properties from weirdgloop@$COMMIT ($DATE)"
